name: Test and Build

on:
  push:
    branches:
      - $default_branch
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and prepare dependencies
        uses: ./.github/workflows/install
      - name: Lint code
        run: npm run lint:ci
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and prepare dependencies
        uses: ./.github/workflows/install
      - name: Run type checking
        run: npm run test:types
      - name: Run unit tests
        run: num run test:unit:ci
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and prepare dependencies
        uses: ./.github/workflows/install
      - name: Build project
        run: npm run build

