name: Deploy

on:
    workflow_run:
      workflows: [Test And Build]
      types: [completed]
    push:
        branches:
            - master
            - $default_branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Using Node.JS
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy project
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

