name: 'Prepare dependencies'
description: 'Install and caching dependencies'

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3
      - name: Use Node.JS
        uses: actions/setup-node@3
        with:
          node-version-file: '.nvmrc'
      - name: Install deps
        env:
          CI: true
        run: npm ci
